name: vivado
'on':
  push:
    branches:
      - feature/testing
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
        
      - name : Install vivado 
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO vivado_installer.run https://www.xilinx.com/bin/public/openDownload?filename=Xilinx_Vivado_SDK_2021.1_0526_2254_Lin64.bin
          chmod +x vivado_installer.run
          sudo ./vivado_installer.run --agree 3rdPartyEULA,WebTalkTerms,XilinxEULA --noexec --target vivado_installer
          sudo ./vivado_installer/xsetup --agree 3rdPartyEULA,WebTalkTerms,XilinxEULA --batch Install --config install_config.txt
