name: vivado
'on':
  push:
    branches:
      - feature/testing
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O vivado_installer.run "https://www.xilinx.com/bin/public/openDownload?filename=Xilinx_Vivado_SDK_2021.1_0526_2254_Lin64.bin"
  Job2:
    name: demo
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run : echo "demo2"
