name: vivado
'on':
  push:
    branches:
      - feature/testing
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
        
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y default-jre
      
      - name: Download Vivado installer
        run: wget https://www.xilinx.com/member/forms/download/xef.html?filename=Xilinx_Vivado_SDK_2021.1_0526_2254.tar.gz -O vivado.tar.gz

      - name: Extract Vivado installer
        run: tar xvf vivado.tar.gz

      - name: Install Vivado
        run: ./Xilinx_Vivado_SDK_2021.1_0526_2254/xsetup --agree 3rdPartyEULA,WebTalkTerms,XilinxEULA --batch Install

      - name: Setup Vivado environment
        run: source /opt/Xilinx/Vivado/2021.1/settings64.sh
