name: vivado
'on':
  push:
    branches:
      - feature/testing
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
        
      - name : Install vivado 
        run: |
          pwd && ls
          sudo ./vivado_installer.run --agree 3rdPartyEULA,WebTalkTerms,XilinxEULA --noexec --target vivado_installer

