name: vivado
'on':
  push:
    branches:
      - feature/testing
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
        
      - name : Install vivado 
        run: |
          ls
